//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestingAPIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class studentmaster
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string rollno { get; set; }
        public string @class { get; set; }
        public string address { get; set; }
    }
}
